// Prisma Recap, Relationships in Prisma

// What are ORMs?

// ORMs let you easily interact with your database without worrying too much about SQL syntax.e.g., Prisma.

// Benefits -
// 1. Simpler syntax
// 2.  you can flip databases
// 3. Type safety (client.query gives back any type)
// 4. Automatic migrations


// Official Definition of Prisma -
// Prisma unlocks a new level of developer experience when working with databases thanks to its intuitive data model, automated migrations, type-safety and auto-completion.



// Installing prisma in a fresh app

// Run the following commands -
// 1. npm init -y
// 2. npm install prisma typescript ts-node @types/node --save-dev
// 3. npx tsc --init

// Now change rootDir to src and outDir to dist in tsconfig.json

// 4. npx prisma init --> creates schema.prisma file

// You can set the databse you want to use in the schema.prisma file. We are using postgres for now.

// Now let's run a postgres database server using docker
//  5. docker run --name MyPostgresServer -e POSTGRES_PASSWORD=mysecretpassword -d -p 5432:5432 postgres

// This will have the following connection string :
//  postgresql://postgres:mysecretpassword@localhost:5432/postgres?sslmode=disable

// Put the above connection string inside .env file. 
// .env files are never uploaded onto github and hence, the database url is protected. schema.prisma file gets the connection string from this .env file.


// Next we create the models in schema.prisma file. It is equivalent to creating tables in sql.

// After that , we generate migrations using this command -

// npx prisma migrate dev --name init_todo_schema    

// This command will convert the models into SQL queries.


// IMPORTANT NOTE - Anytime you update schema.prisma file, you have to re-run the migrate dev command.

// For example, suppose we add an email field in the users model. Then re-run the above command. You'll notice another folder has been created inside the prisma/migrations folder.


// You may now explore your database present inde the docker container using tjhe following commands -

// docker exec -it <container_id> /bin/bash 
// psql -h localhost -U postgres -d postgres
// \dt  



// Autogenerated Clients --> anything that lets you interact with the database is a database client.

// How to generate the client ?
// npx prisma genrate

// This command Generated Prisma Client (v6.14.0) to .\src\generated\prisma 

// now refer to index.ts for CRUD operations.

// Please remeber you need to put the name of the table inside double quotes ("") while viewing it through psql because prisma creates the tables using "".













// Relationships in Prisma
// Prisma let’s you define relationships  to relate tables with each other.

// 1. Types of relationships
// One to One
// One to Many
// Many to One
// Many to Many
 
// 2. For the TODO app, there is a one to many  relationship
// This means that one user can have many todos, but each todo is associated with only one user.

// Refer to one_to_many relationship.webp

// Good example of many to many relationship  --> refer to many_to_many relationship.png



// Let's update the prisma schema 
// Refer to prisma/schema.prisma to see how the relationship has been added.


// model User {
//   id         Int      @id @default(autoincrement())
//   username   String   @unique
//   password   String
//   firstName  String
//   lastName   String
//   todos      Todo[]
// }

// model Todo {
//   id          Int     @id @default(autoincrement())
//   title       String
//   description String
//   done        Boolean @default(false)
//   userId      Int
//   user        User    @relation(fields: [userId], references: [id])
// }


// In this schema:

// - The `User` model has a `todos` field, which is an array of `Todo` objects. This represents the "many" side of the one-to-many relationship.
// - The `Todo` model has a `userId` field, which stores the reference to the associated `User`. It also has a `user` field that establishes the relationship using the `@relation` attribute. The `fields: [userId]` part specifies which field on the `Todo` model is used to store the connection, and `references: [id]` part specifies which field on the `User` model is being referred to.








// Now the last step is to 
// 4. Update the database  and the prisma client 
// npx prisma migrate dev --name relationship
// npx prisma generate


// Now refer to src/index.ts and see the getTodos function.
// But this getTodos function would have ran anyway without the reaktionship that we introduced.

// So now let's see the getTodosAndUserDetails function.

// As you can see in this function, we are able to view the user details only because prisma knows that there exists a relationship between both tables.


// So the benefit of having a relationship is that -
// Now you can't add todos for a non-existing user because foreign key rule is violated.f