// ORMs

// 1. Boring official definition

// ORM stands for Object-Relational Mapping, a programming technique used in software development to convert data between incompatible type systems in object-oriented programming languages. This technique creates a "virtual object database" that can be used from within the programming language.
// ORMs are used to abstract the complexities of the underlying database into simpler, more easily managed objects within the code

// 2. Easier to digest definition
// ORMs let you easily interact with your database without worrying too much about the underlying syntax (SQL language for eg)









// Why ORMs?

// 1. Simpler syntax (converts objects to SQL queries under the hood)
// Refer to ORM advantage_1 image
// You don't have to write SQL in your Nodejs code
// As a developer, you don't have to worry about SQL syntax.

// 2. Abstraction that lets you flip/change the database you are using. Unified API irrespective of the DB
// Refer to primsa abstraction image
// So basically, you can use the same Node.js code for interacting with different databases.

// 3. Type Safety / Auto-completion
// Refer to type safety image
// Non-ORM code does not have type safety and mostly uses the any type. So, ORM help introduce type safety into the code.
// pg library(Non-ORM) does not provide good type safety, but prisma does.

// 4. Automatic Migrations

// Migrations --> Migrations are like a version history for your database structure — they keep track of changes you make to tables, columns, relationships, etc., over time.

// Migration is all the commands that we have to run to reach the current schema of our application.

// A migration is a file that describes how to change your database — like adding a table, renaming a column, or deleting a field — and also how to undo that change if needed.

// In case of a simple Postgres app, it’s very hard to keep track of all the commands that were ran that led to the current schema of the table.

// What commands were run to reach that structure of the schema we need to implement. ORMs give you a centralized place where all of these migrations are present.

// ORMs (or more specifically Prisma) maintains all of these commands for you.

// This helps in migrating from one database to a new database ensuring that the schema remains the same.


// Refer to this link for real life example --> https://github.com/code100x/cms/tree/main/prisma/migrations











// What is Prisma?

// Prisma is a node.js specific ORM. Prisma offers four things -

// 1. Data Model --> In a single file, define your schema. What it looks like, what tables you have, what field each table has, how are rows related to each other.

// In schema.prisma file, we just have to define the schema once ensuring that the schema is clearly defined with all its tables. This is the intuitive data model.

// Prisma converts this data model into SQL queries which you don't have to worry about

// 2. Automated migrations --> Prisma generates and runs database migrations based on changes to the Prisma schema. Prisma keeps tracks of all the migrations that have happened.

// 3. Type-safety --> Prisma generates a type-safe database client based on the Prisma schema.

// 4. Auto-completion


















// Installing prisma in a fresh app

// 1. npm init -y

// 2. npm install prisma typescript ts-node @types/node --save-dev

// 3. npx tsc --init
// Change `rootDir` to `src`
// Change `outDir` to `dist`

// 4. npx prisma init


// Prisma lets you chose between a few databases (MySQL, Postgres, Mongo)
// You can update prisma/schema.prisma  to setup what database you want to use. 
// Also replace the database url with your test url for now
// Good to have the VSCode extension that lets you visualise prisma better
















// Step 6 - Defining the Data Model
// Prisma expects you to define the shape of your data in the schema.prisma  file

// If your final app will have a Users table, it would look like this in the schema.prisma  file
// model User {
//   id         Int      @id @default(autoincrement())
//   username   String   @unique
//   password   String
//   firstName  String
//   lastName   String
// }



// Generate Migrations

// You have created a single schema file. You haven’t yet run the CREATE TABLE  commands. To run those and create migration files , run

// npx prisma migrate dev --name Initialize the schema

// in the above command , "Initalize the schema" is a random name given to the migration

// Your DB should now have the updated schema

// So, now prisma has not only created a migration file but also ran some SQL commands for designing the schema.

// you can explore your database on console.neon.tech












// Autogenerated Clients

// Prisma needs to create clients or javascript classes that index.ts can use

// Until now the steps have been -

// 1. create the schema.prisma file by initalizing the prisma project
// 2. run the migration command to create migration.sql
// 3. we run a command that generates the clients



// Client represents all the functions that convert 
// User.create({email: "harkirat@gmail.com"})

// into
// INSERT INTO users VALUES ...


// This "User" is a client.


// How to generate the client?
// npx prisma generate

// An autogenerated client is a piece of code automatically created for you that lets your application interact with a backend API or database easily and safely — without you having to manually write all the logic for queries or requests.

// Now these clients offer us a few function
// Refer to index.ts file from week-10-2/src
// 1. insert 
// 2. update
// 3. find